name: somnio_test
description: "Somnio Technical Test"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Graphics
  cupertino_icons: ^1.0.6
  phosphor_flutter: ^2.1.0
  animate_do: ^3.3.4

  # Utils
  intl: ^0.19.0
  intl_utils: ^2.8.7
  logger: ^2.3.0
  envied: ^0.5.4+1

  # Packages
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  http: ^1.2.1
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.5.0+1
  envied_generator: ^0.5.4+1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: IntlTranslations
  main_locale: es
  arb_dir: lib/l10n
  output_dir: lib/gen

flutter_gen:
  output: lib/gen